/**
 * Clean up stale test data for John Doe (patient d0000000-...01).
 *
 * Deletes all non-seed rows generated by prior test runs, leaving only
 * the 3 seed encounters, 3 seed clinical notes, and 3 seed assessment scores.
 * Resets sessions_used back to the seed value of 3.
 *
 * FK-safe deletion order: child rows first, parent rows last.
 *
 * Usage: npx tsx scripts/cleanup-test-data.ts
 */

import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
import { createAdminClient } from '../src/lib/supabase/admin';

const ORG_ID = 'a0000000-0000-0000-0000-000000000001';
const JOHN_DOE_ID = 'd0000000-0000-0000-0000-000000000001';

// Seed encounter IDs to preserve
const SEED_ENCOUNTER_IDS = [
  'e0000000-0000-0000-0000-000000000001',
  'e0000000-0000-0000-0000-000000000002',
  'e0000000-0000-0000-0000-000000000003',
];

// Seed clinical note IDs to preserve
const SEED_NOTE_IDS = [
  'f0000000-0000-0000-0000-000000000001',
  'f0000000-0000-0000-0000-000000000002',
  'f0000000-0000-0000-0000-000000000003',
];

// Seed assessment score IDs to preserve
const SEED_SCORE_IDS = [
  'e1000000-0000-0000-0000-000000000001',
  'e1000000-0000-0000-0000-000000000002',
  'e1000000-0000-0000-0000-000000000003',
];

async function main() {
  const client = createAdminClient();

  console.log('=== Cleaning up stale test data for John Doe ===\n');

  // --- 1. claim_diagnoses (references billing_claims) ---
  {
    // Get John Doe's claim IDs first
    const { data: claims } = await client
      .from('billing_claims')
      .select('id')
      .eq('patient_id', JOHN_DOE_ID);
    const claimIds = claims?.map((c) => c.id) ?? [];

    if (claimIds.length > 0) {
      const { error, count } = await client
        .from('claim_diagnoses')
        .delete({ count: 'exact' })
        .in('claim_id', claimIds);
      console.log(`claim_diagnoses: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);

      // --- 2. claim_line_items (references billing_claims) ---
      const { error: lineErr, count: lineCount } = await client
        .from('claim_line_items')
        .delete({ count: 'exact' })
        .in('claim_id', claimIds);
      console.log(`claim_line_items: deleted ${lineCount ?? 0} rows${lineErr ? ` (ERROR: ${lineErr.message})` : ''}`);
    } else {
      console.log('claim_diagnoses: 0 rows (no claims found)');
      console.log('claim_line_items: 0 rows (no claims found)');
    }
  }

  // --- 3. billing_claims ---
  {
    const { error, count } = await client
      .from('billing_claims')
      .delete({ count: 'exact' })
      .eq('patient_id', JOHN_DOE_ID);
    console.log(`billing_claims: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 4. note_signatures for non-seed notes ---
  {
    // Get non-seed note IDs for John Doe
    const { data: nonSeedNotes } = await client
      .from('clinical_notes')
      .select('id')
      .eq('patient_id', JOHN_DOE_ID)
      .not('id', 'in', `(${SEED_NOTE_IDS.join(',')})`);
    const nonSeedNoteIds = nonSeedNotes?.map((n) => n.id) ?? [];

    if (nonSeedNoteIds.length > 0) {
      const { error, count } = await client
        .from('note_signatures')
        .delete({ count: 'exact' })
        .in('clinical_note_id', nonSeedNoteIds);
      console.log(`note_signatures (non-seed): deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
    } else {
      console.log('note_signatures (non-seed): 0 rows (no non-seed notes)');
    }
  }

  // --- 5. clinical_notes — non-seed only ---
  {
    const { error, count } = await client
      .from('clinical_notes')
      .delete({ count: 'exact' })
      .eq('patient_id', JOHN_DOE_ID)
      .not('id', 'in', `(${SEED_NOTE_IDS.join(',')})`);
    console.log(`clinical_notes (non-seed): deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 6. note_drafts (all for this org — no seed drafts exist) ---
  {
    const { error, count } = await client
      .from('note_drafts')
      .delete({ count: 'exact' })
      .eq('org_id', ORG_ID);
    console.log(`note_drafts: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 7. ai_proposed_actions (references ai_runs) ---
  {
    const { error, count } = await client
      .from('ai_proposed_actions')
      .delete({ count: 'exact' })
      .eq('org_id', ORG_ID);
    console.log(`ai_proposed_actions: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 8. ai_steps (cascades from ai_runs, but delete explicitly for count) ---
  // ai_steps has no org_id — get run IDs first
  {
    const { data: runs } = await client
      .from('ai_runs')
      .select('id')
      .eq('org_id', ORG_ID);
    const runIds = runs?.map((r) => r.id) ?? [];

    if (runIds.length > 0) {
      const { error, count } = await client
        .from('ai_steps')
        .delete({ count: 'exact' })
        .in('run_id', runIds);
      console.log(`ai_steps: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
    } else {
      console.log('ai_steps: 0 rows (no ai_runs found)');
    }
  }

  // --- 9. ai_clarifications (references ai_runs) ---
  {
    const { error, count } = await client
      .from('ai_clarifications')
      .delete({ count: 'exact' })
      .eq('org_id', ORG_ID);
    console.log(`ai_clarifications: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 10. ai_runs ---
  {
    const { error, count } = await client
      .from('ai_runs')
      .delete({ count: 'exact' })
      .eq('org_id', ORG_ID);
    console.log(`ai_runs: deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 11. assessment_scores — non-seed only ---
  {
    const { error, count } = await client
      .from('assessment_scores')
      .delete({ count: 'exact' })
      .eq('patient_id', JOHN_DOE_ID)
      .not('id', 'in', `(${SEED_SCORE_IDS.join(',')})`);
    console.log(`assessment_scores (non-seed): deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 12. encounters — non-seed only ---
  {
    const { error, count } = await client
      .from('encounters')
      .delete({ count: 'exact' })
      .eq('patient_id', JOHN_DOE_ID)
      .not('id', 'in', `(${SEED_ENCOUNTER_IDS.join(',')})`);
    console.log(`encounters (non-seed): deleted ${count ?? 0} rows${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- 13. Reset sessions_used to seed value ---
  {
    const { error, count } = await client
      .from('patient_insurance')
      .update({ sessions_used: 3 })
      .eq('patient_id', JOHN_DOE_ID)
      .eq('org_id', ORG_ID);
    console.log(`patient_insurance: reset sessions_used = 3${error ? ` (ERROR: ${error.message})` : ''}`);
  }

  // --- Verification ---
  console.log('\n=== Verification ===\n');

  const { data: encounters } = await client
    .from('encounters')
    .select('id, encounter_date, status')
    .eq('patient_id', JOHN_DOE_ID)
    .order('encounter_date');
  console.log(`Encounters for John Doe: ${encounters?.length ?? 0}`);
  encounters?.forEach((e) => console.log(`  - ${e.id.substring(0, 12)}... | ${e.encounter_date} | ${e.status}`));

  const { data: notes } = await client
    .from('clinical_notes')
    .select('id, note_type, status')
    .eq('patient_id', JOHN_DOE_ID);
  console.log(`Clinical notes for John Doe: ${notes?.length ?? 0}`);
  notes?.forEach((n) => console.log(`  - ${n.id.substring(0, 12)}... | ${n.note_type} | ${n.status}`));

  const { data: scores } = await client
    .from('assessment_scores')
    .select('id, measure_type, score, administered_at')
    .eq('patient_id', JOHN_DOE_ID)
    .order('administered_at');
  console.log(`Assessment scores for John Doe: ${scores?.length ?? 0}`);
  scores?.forEach((s) => console.log(`  - ${s.id.substring(0, 12)}... | ${s.measure_type}: ${s.score} | ${s.administered_at}`));

  const { data: insurance } = await client
    .from('patient_insurance')
    .select('sessions_used, authorized_sessions')
    .eq('patient_id', JOHN_DOE_ID)
    .single();
  console.log(`Insurance: sessions_used = ${insurance?.sessions_used} / ${insurance?.authorized_sessions}`);

  const { data: aiRuns } = await client
    .from('ai_runs')
    .select('id')
    .eq('org_id', ORG_ID);
  console.log(`AI runs remaining: ${aiRuns?.length ?? 0}`);

  const { data: drafts } = await client
    .from('note_drafts')
    .select('id')
    .eq('org_id', ORG_ID);
  console.log(`Note drafts remaining: ${drafts?.length ?? 0}`);

  console.log('\n✓ Cleanup complete');
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
